//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siemens.EHealth.Etee.Crypto.Library.ServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", ConfigurationName="ServiceClient.KgssPortType")]
    public interface KgssPortType {
        
        // CODEGEN: Generating message contract since the operation GetNewKey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EteeResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse1 GetNewKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetKey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EteeResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse1 GetKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    public partial class GetNewKeyRequest : RequestType {
        
        private SealedContentType sealedNewKeyRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SealedContentType SealedNewKeyRequest {
            get {
                return this.sealedNewKeyRequestField;
            }
            set {
                this.sealedNewKeyRequestField = value;
                this.RaisePropertyChanged("SealedNewKeyRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    public partial class SealedContentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] sealedContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] SealedContent {
            get {
                return this.sealedContentField;
            }
            set {
                this.sealedContentField = value;
                this.RaisePropertyChanged("SealedContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ErrorType", Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol")]
    public partial class ErrorType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:1_0:protocol")]
    public partial class ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status statusField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:be:fgov:ehealth:commons:1_0:core", Order=0)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:commons:1_0:core")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private LocalisedString[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LocalisedString[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:1_0:core")]
    public partial class LocalisedString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LangageType langField;
        
        private bool langFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LangageType Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LangSpecified {
            get {
                return this.langFieldSpecified;
            }
            set {
                this.langFieldSpecified = value;
                this.RaisePropertyChanged("LangSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:1_0:core")]
    public enum LangageType {
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol")]
    public partial class IdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        private string applicationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
                this.RaisePropertyChanged("ApplicationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etee:commons:1_0:etee")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private LocalisedString[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LocalisedString[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etee:commons:1_0:etee")]
    public partial class EteeResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EteeResponseTypeStatus statusField;
        
        private ErrorType[] errorField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public EteeResponseTypeStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ErrorType[] Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:commons:1_0:etee")]
    public partial class EteeResponseTypeStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:1_0:protocol")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    public partial class GetNewKeyResponse : EteeResponseType {
        
        private SealedContentType sealedNewKeyResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SealedContentType SealedNewKeyResponse {
            get {
                return this.sealedNewKeyResponseField;
            }
            set {
                this.sealedNewKeyResponseField = value;
                this.RaisePropertyChanged("SealedNewKeyResponse");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewKeyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest GetNewKeyRequest;
        
        public GetNewKeyRequest1() {
        }
        
        public GetNewKeyRequest1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest GetNewKeyRequest) {
            this.GetNewKeyRequest = GetNewKeyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewKeyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse GetNewKeyResponse;
        
        public GetNewKeyResponse1() {
        }
        
        public GetNewKeyResponse1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse GetNewKeyResponse) {
            this.GetNewKeyResponse = GetNewKeyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    public partial class GetKeyRequest : RequestType {
        
        private SealedContentType sealedKeyRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SealedContentType SealedKeyRequest {
            get {
                return this.sealedKeyRequestField;
            }
            set {
                this.sealedKeyRequestField = value;
                this.RaisePropertyChanged("SealedKeyRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    public partial class GetKeyResponse : EteeResponseType {
        
        private SealedContentType sealedKeyResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SealedContentType SealedKeyResponse {
            get {
                return this.sealedKeyResponseField;
            }
            set {
                this.sealedKeyResponseField = value;
                this.RaisePropertyChanged("SealedKeyResponse");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest GetKeyRequest;
        
        public GetKeyRequest1() {
        }
        
        public GetKeyRequest1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest GetKeyRequest) {
            this.GetKeyRequest = GetKeyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse GetKeyResponse;
        
        public GetKeyResponse1() {
        }
        
        public GetKeyResponse1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse GetKeyResponse) {
            this.GetKeyResponse = GetKeyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KgssPortTypeChannel : Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KgssPortTypeClient : System.ServiceModel.ClientBase<Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType>, Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType {
        
        public KgssPortTypeClient() {
        }
        
        public KgssPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KgssPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KgssPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KgssPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse1 Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType.GetNewKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest1 request) {
            return base.Channel.GetNewKey(request);
        }
        
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse GetNewKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest GetNewKeyRequest) {
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest1 inValue = new Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyRequest1();
            inValue.GetNewKeyRequest = GetNewKeyRequest;
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetNewKeyResponse1 retVal = ((Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType)(this)).GetNewKey(inValue);
            return retVal.GetNewKeyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse1 Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType.GetKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest1 request) {
            return base.Channel.GetKey(request);
        }
        
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse GetKey(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest GetKeyRequest) {
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest1 inValue = new Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyRequest1();
            inValue.GetKeyRequest = GetKeyRequest;
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetKeyResponse1 retVal = ((Siemens.EHealth.Etee.Crypto.Library.ServiceClient.KgssPortType)(this)).GetKey(inValue);
            return retVal.GetKeyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol", ConfigurationName="ServiceClient.EtkDepotPortType")]
    public interface EtkDepotPortType {
        
        // CODEGEN: Generating message contract since the operation GetEtk is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EteeResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse1 GetEtk(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol")]
    public partial class GetEtkRequest : RequestType {
        
        private IdentifierType[] searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identifier", IsNullable=false)]
        public IdentifierType[] SearchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("SearchCriteria");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol")]
    public partial class GetEtkResponse : ResponseType {
        
        private IdentifierType[] givenSearchCriteriaField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identifier", IsNullable=false)]
        public IdentifierType[] GivenSearchCriteria {
            get {
                return this.givenSearchCriteriaField;
            }
            set {
                this.givenSearchCriteriaField = value;
                this.RaisePropertyChanged("GivenSearchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ETK", typeof(byte[]), DataType="base64Binary", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(ErrorType1), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("MatchingEtk", typeof(MatchingEtk), Order=1)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol")]
    public partial class MatchingEtk : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentifierType[] identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identifier", Order=0)]
        public IdentifierType[] Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEtkRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest GetEtkRequest;
        
        public GetEtkRequest1() {
        }
        
        public GetEtkRequest1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest GetEtkRequest) {
            this.GetEtkRequest = GetEtkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEtkResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:fgov:ehealth:etkdepot:1_0:protocol", Order=0)]
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse GetEtkResponse;
        
        public GetEtkResponse1() {
        }
        
        public GetEtkResponse1(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse GetEtkResponse) {
            this.GetEtkResponse = GetEtkResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EtkDepotPortTypeChannel : Siemens.EHealth.Etee.Crypto.Library.ServiceClient.EtkDepotPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtkDepotPortTypeClient : System.ServiceModel.ClientBase<Siemens.EHealth.Etee.Crypto.Library.ServiceClient.EtkDepotPortType>, Siemens.EHealth.Etee.Crypto.Library.ServiceClient.EtkDepotPortType {
        
        public EtkDepotPortTypeClient() {
        }
        
        public EtkDepotPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtkDepotPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtkDepotPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtkDepotPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse1 Siemens.EHealth.Etee.Crypto.Library.ServiceClient.EtkDepotPortType.GetEtk(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest1 request) {
            return base.Channel.GetEtk(request);
        }
        
        public Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse GetEtk(Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest GetEtkRequest) {
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest1 inValue = new Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkRequest1();
            inValue.GetEtkRequest = GetEtkRequest;
            Siemens.EHealth.Etee.Crypto.Library.ServiceClient.GetEtkResponse1 retVal = ((Siemens.EHealth.Etee.Crypto.Library.ServiceClient.EtkDepotPortType)(this)).GetEtk(inValue);
            return retVal.GetEtkResponse;
        }
    }
}
