//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egelke.EHealth.Client.GenIns
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SystemError : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SystemError", "urn:be:fgov:ehealth:errors:soa:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SOAErrorType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SOAErrorType", "urn:be:fgov:ehealth:errors:soa:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ErrorType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ErrorType", "urn:be:fgov:ehealth:errors:core:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.Sign, Namespace = "urn:be:fgov:ehealth:genericinsurability:protocol:v1", ConfigurationName = "GenInsV1", Name = "GenericInsurabilityPort")]
    public interface GenericInsurabilityPortType
    {
        
        // CODEGEN: Generating message contract since the operation getInsurability is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:genericinsurability:protocol:v1:GetInsurability", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.GenIns.SystemError), Action="urn:be:fgov:ehealth:genericinsurability:protocol:v1:GetInsurability", Name="SystemError", Namespace="urn:be:fgov:ehealth:errors:soa:v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Egelke.EHealth.Client.GenIns.getInsurabilityResponse getInsurability(Egelke.EHealth.Client.GenIns.getInsurabilityRequest request);
        
        // CODEGEN: Generating message contract since the operation getInsurabilityAsFlat is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:genericinsurability:protocol:v1:GetInsurabilityAsFlat", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.GenIns.SystemError), Action="urn:be:fgov:ehealth:genericinsurability:protocol:v1:GetInsurabilityAsFlat", Name="SystemError", Namespace="urn:be:fgov:ehealth:errors:soa:v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatResponse getInsurabilityAsFlat(Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1")]
    public partial class GetInsurabilityAsXmlOrFlatRequestType : RequestType
    {
        
        private CommonInputType commonInputField;
        
        private RecordCommonInputType recordCommonInputField;
        
        private SingleInsurabilityRequestType requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonInputType CommonInput
        {
            get
            {
                return this.commonInputField;
            }
            set
            {
                this.commonInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RecordCommonInputType RecordCommonInput
        {
            get
            {
                return this.recordCommonInputField;
            }
            set
            {
                this.recordCommonInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SingleInsurabilityRequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class CommonInputType
    {
        
        private RequestType1 requestField;
        
        private OriginType originField;
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestType1 Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OriginType Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestType", Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class RequestType1
    {
        
        private bool isTestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsTest
        {
            get
            {
                return this.isTestField;
            }
            set
            {
                this.isTestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class InsurabilityItemType
    {
        
        private string regNrWithMutField;
        
        private string mutualityField;
        
        private PeriodType periodField;
        
        private string cT1Field;
        
        private string cT2Field;
        
        private string paymentApprovalField;
        
        private System.DateTime insurabilityDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegNrWithMut
        {
            get
            {
                return this.regNrWithMutField;
            }
            set
            {
                this.regNrWithMutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mutuality
        {
            get
            {
                return this.mutualityField;
            }
            set
            {
                this.mutualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CT1
        {
            get
            {
                return this.cT1Field;
            }
            set
            {
                this.cT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CT2
        {
            get
            {
                return this.cT2Field;
            }
            set
            {
                this.cT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PaymentApproval
        {
            get
            {
                return this.paymentApprovalField;
            }
            set
            {
                this.paymentApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime InsurabilityDate
        {
            get
            {
                return this.insurabilityDateField;
            }
            set
            {
                this.insurabilityDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class PeriodType
    {
        
        private System.DateTime periodStartField;
        
        private bool periodStartFieldSpecified;
        
        private System.DateTime periodEndField;
        
        private bool periodEndFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.periodStartField;
            }
            set
            {
                this.periodStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodStartSpecified
        {
            get
            {
                return this.periodStartFieldSpecified;
            }
            set
            {
                this.periodStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.periodEndField;
            }
            set
            {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodEndSpecified
        {
            get
            {
                return this.periodEndFieldSpecified;
            }
            set
            {
                this.periodEndFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class InsurabilityListType
    {
        
        private InsurabilityItemType[] insurabilityItemField;
        
        private bool truncatedField;
        
        private bool truncatedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InsurabilityItem", Order=0)]
        public InsurabilityItemType[] InsurabilityItem
        {
            get
            {
                return this.insurabilityItemField;
            }
            set
            {
                this.insurabilityItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Truncated
        {
            get
            {
                return this.truncatedField;
            }
            set
            {
                this.truncatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TruncatedSpecified
        {
            get
            {
                return this.truncatedFieldSpecified;
            }
            set
            {
                this.truncatedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class MedicalHouseType
    {
        
        private System.DateTime periodStartField;
        
        private System.DateTime periodEndField;
        
        private bool periodEndFieldSpecified;
        
        private bool nurseField;
        
        private bool nurseFieldSpecified;
        
        private bool medicalField;
        
        private bool medicalFieldSpecified;
        
        private bool kineField;
        
        private bool kineFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.periodStartField;
            }
            set
            {
                this.periodStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.periodEndField;
            }
            set
            {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodEndSpecified
        {
            get
            {
                return this.periodEndFieldSpecified;
            }
            set
            {
                this.periodEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Nurse
        {
            get
            {
                return this.nurseField;
            }
            set
            {
                this.nurseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NurseSpecified
        {
            get
            {
                return this.nurseFieldSpecified;
            }
            set
            {
                this.nurseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Medical
        {
            get
            {
                return this.medicalField;
            }
            set
            {
                this.medicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicalSpecified
        {
            get
            {
                return this.medicalFieldSpecified;
            }
            set
            {
                this.medicalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Kine
        {
            get
            {
                return this.kineField;
            }
            set
            {
                this.kineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KineSpecified
        {
            get
            {
                return this.kineFieldSpecified;
            }
            set
            {
                this.kineFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class HospitalizedType
    {
        
        private string hospitalField;
        
        private System.DateTime admissionDateField;
        
        private bool admissionDateFieldSpecified;
        
        private string admissionServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Hospital
        {
            get
            {
                return this.hospitalField;
            }
            set
            {
                this.hospitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime AdmissionDate
        {
            get
            {
                return this.admissionDateField;
            }
            set
            {
                this.admissionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdmissionDateSpecified
        {
            get
            {
                return this.admissionDateFieldSpecified;
            }
            set
            {
                this.admissionDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AdmissionService
        {
            get
            {
                return this.admissionServiceField;
            }
            set
            {
                this.admissionServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class PaymentType
    {
        
        private bool paymentByIoField;
        
        private string[] maxInvoicedField;
        
        private bool specialSocialCategoryField;
        
        private bool specialSocialCategoryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool PaymentByIo
        {
            get
            {
                return this.paymentByIoField;
            }
            set
            {
                this.paymentByIoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaxInvoiced", DataType="gYear", Order=1)]
        public string[] MaxInvoiced
        {
            get
            {
                return this.maxInvoicedField;
            }
            set
            {
                this.maxInvoicedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool SpecialSocialCategory
        {
            get
            {
                return this.specialSocialCategoryField;
            }
            set
            {
                this.specialSocialCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpecialSocialCategorySpecified
        {
            get
            {
                return this.specialSocialCategoryFieldSpecified;
            }
            set
            {
                this.specialSocialCategoryFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class TransferType
    {
        
        private InsuranceOrgType insuranceOrgField;
        
        private bool insuranceOrgFieldSpecified;
        
        private System.DateTime transferDateField;
        
        private TransferDirectionType directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InsuranceOrgType InsuranceOrg
        {
            get
            {
                return this.insuranceOrgField;
            }
            set
            {
                this.insuranceOrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsuranceOrgSpecified
        {
            get
            {
                return this.insuranceOrgFieldSpecified;
            }
            set
            {
                this.insuranceOrgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime TransferDate
        {
            get
            {
                return this.transferDateField;
            }
            set
            {
                this.transferDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransferDirectionType Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum InsuranceOrgType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")]
        Item200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("300")]
        Item300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("400")]
        Item400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")]
        Item500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("600")]
        Item600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("900")]
        Item900,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum TransferDirectionType
    {
        
        /// <remarks/>
        toOtherIo,
        
        /// <remarks/>
        fromOtherIo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class GeneralSituationType
    {
        
        private TransferType[] transferField;
        
        private EventType eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transfer", Order=0)]
        public TransferType[] Transfer
        {
            get
            {
                return this.transferField;
            }
            set
            {
                this.transferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EventType Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum EventType
    {
        
        /// <remarks/>
        changeDuring,
        
        /// <remarks/>
        multiple,
        
        /// <remarks/>
        closedBefore,
        
        /// <remarks/>
        startLater,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class InsurabilityResponseDetailType
    {
        
        private GeneralSituationType generalSituationField;
        
        private PaymentType paymentField;
        
        private HospitalizedType hospitalizedField;
        
        private MedicalHouseType medicalHouseField;
        
        private InsurabilityListType insurabilityListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GeneralSituationType GeneralSituation
        {
            get
            {
                return this.generalSituationField;
            }
            set
            {
                this.generalSituationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaymentType Payment
        {
            get
            {
                return this.paymentField;
            }
            set
            {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HospitalizedType Hospitalized
        {
            get
            {
                return this.hospitalizedField;
            }
            set
            {
                this.hospitalizedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MedicalHouseType MedicalHouse
        {
            get
            {
                return this.medicalHouseField;
            }
            set
            {
                this.medicalHouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public InsurabilityListType InsurabilityList
        {
            get
            {
                return this.insurabilityListField;
            }
            set
            {
                this.insurabilityListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class CareReceiverDetailType
    {
        
        private string inssField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private System.DateTime deceasedField;
        
        private bool deceasedFieldSpecified;
        
        private SexType sexField;
        
        private bool sexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Inss
        {
            get
            {
                return this.inssField;
            }
            set
            {
                this.inssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime Birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthdaySpecified
        {
            get
            {
                return this.birthdayFieldSpecified;
            }
            set
            {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime Deceased
        {
            get
            {
                return this.deceasedField;
            }
            set
            {
                this.deceasedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeceasedSpecified
        {
            get
            {
                return this.deceasedFieldSpecified;
            }
            set
            {
                this.deceasedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SexType Sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SexSpecified
        {
            get
            {
                return this.sexFieldSpecified;
            }
            set
            {
                this.sexFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum SexType
    {
        
        /// <remarks/>
        male,
        
        /// <remarks/>
        female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class DetailType
    {
        
        private string detailCodeField;
        
        private string locationField;
        
        private MessageType messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DetailCode
        {
            get
            {
                return this.detailCodeField;
            }
            set
            {
                this.detailCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MessageType Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class MessageType
    {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class MessageFaultType
    {
        
        private FaultCodeType faultCodeField;
        
        private string faultSourceField;
        
        private InsuranceOrgInOneCharType[] multiIOField;
        
        private MessageType messageField;
        
        private DetailType[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultCodeType FaultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FaultSource
        {
            get
            {
                return this.faultSourceField;
            }
            set
            {
                this.faultSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IO", IsNullable=false)]
        public InsuranceOrgInOneCharType[] MultiIO
        {
            get
            {
                return this.multiIOField;
            }
            set
            {
                this.multiIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MessageType Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detail", IsNullable=false)]
        public DetailType[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum FaultCodeType
    {
        
        /// <remarks/>
        INPUT_ERROR,
        
        /// <remarks/>
        NO_IO_ERROR,
        
        /// <remarks/>
        MULTIIO_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum InsuranceOrgInOneCharType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class SingleInsurabilityResponseType
    {
        
        private object[] itemsField;
        
        private InsurabilityRequestDetailType insurabilityRequestDetailField;
        
        private MessageNameType messageNameField;
        
        private bool messageNameFieldSpecified;
        
        private string versionField;
        
        private bool duplicateField;
        
        private bool duplicateFieldSpecified;
        
        private bool testFlagField;
        
        private bool testFlagFieldSpecified;
        
        private string senderReferenceField;
        
        private string receiverReferenceField;
        
        private bool synchronousField;
        
        private bool synchronousFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CareReceiverDetail", typeof(CareReceiverDetailType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CareReceiverId", typeof(CareReceiverIdType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InsurabilityResponseDetail", typeof(InsurabilityResponseDetailType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MessageFault", typeof(MessageFaultType), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InsurabilityRequestDetailType InsurabilityRequestDetail
        {
            get
            {
                return this.insurabilityRequestDetailField;
            }
            set
            {
                this.insurabilityRequestDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MessageNameType MessageName
        {
            get
            {
                return this.messageNameField;
            }
            set
            {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageNameSpecified
        {
            get
            {
                return this.messageNameFieldSpecified;
            }
            set
            {
                this.messageNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Duplicate
        {
            get
            {
                return this.duplicateField;
            }
            set
            {
                this.duplicateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuplicateSpecified
        {
            get
            {
                return this.duplicateFieldSpecified;
            }
            set
            {
                this.duplicateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool TestFlag
        {
            get
            {
                return this.testFlagField;
            }
            set
            {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestFlagSpecified
        {
            get
            {
                return this.testFlagFieldSpecified;
            }
            set
            {
                this.testFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SenderReference
        {
            get
            {
                return this.senderReferenceField;
            }
            set
            {
                this.senderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReceiverReference
        {
            get
            {
                return this.receiverReferenceField;
            }
            set
            {
                this.receiverReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Synchronous
        {
            get
            {
                return this.synchronousField;
            }
            set
            {
                this.synchronousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SynchronousSpecified
        {
            get
            {
                return this.synchronousFieldSpecified;
            }
            set
            {
                this.synchronousFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class CareReceiverIdType
    {
        
        private string inssField;
        
        private string regNrWithMutField;
        
        private string mutualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Inss
        {
            get
            {
                return this.inssField;
            }
            set
            {
                this.inssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegNrWithMut
        {
            get
            {
                return this.regNrWithMutField;
            }
            set
            {
                this.regNrWithMutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mutuality
        {
            get
            {
                return this.mutualityField;
            }
            set
            {
                this.mutualityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class InsurabilityRequestDetailType
    {
        
        private InsurabilityRequestTypeType insurabilityRequestTypeField;
        
        private PeriodType periodField;
        
        private InsurabilityContactTypeType insurabilityContactTypeField;
        
        private string insurabilityReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InsurabilityRequestTypeType InsurabilityRequestType
        {
            get
            {
                return this.insurabilityRequestTypeField;
            }
            set
            {
                this.insurabilityRequestTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public InsurabilityContactTypeType InsurabilityContactType
        {
            get
            {
                return this.insurabilityContactTypeField;
            }
            set
            {
                this.insurabilityContactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InsurabilityReference
        {
            get
            {
                return this.insurabilityReferenceField;
            }
            set
            {
                this.insurabilityReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum InsurabilityRequestTypeType
    {
        
        /// <remarks/>
        information,
        
        /// <remarks/>
        invoicing,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum InsurabilityContactTypeType
    {
        
        /// <remarks/>
        ambulatory_care,
        
        /// <remarks/>
        hospitalized_for_day,
        
        /// <remarks/>
        hospitalized_elsewhere,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public enum MessageNameType
    {
        
        /// <remarks/>
        M801000,
        
        /// <remarks/>
        M801000ERR,
        
        /// <remarks/>
        M801001,
        
        /// <remarks/>
        M801900,
        
        /// <remarks/>
        M410000,
        
        /// <remarks/>
        M410001,
        
        /// <remarks/>
        M410000ERR,
        
        /// <remarks/>
        M410900,
        
        /// <remarks/>
        M410908,
        
        /// <remarks/>
        M410999,
        
        /// <remarks/>
        M420000,
        
        /// <remarks/>
        M420001,
        
        /// <remarks/>
        M420000ERR,
        
        /// <remarks/>
        M420900,
        
        /// <remarks/>
        M420999,
        
        /// <remarks/>
        M430000,
        
        /// <remarks/>
        M430001,
        
        /// <remarks/>
        M430000ERR,
        
        /// <remarks/>
        M891000,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class RecordCommonOutputType
    {
        
        private decimal inputReferenceField;
        
        private bool inputReferenceFieldSpecified;
        
        private decimal outputReferenceField;
        
        private bool outputReferenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InputReferenceSpecified
        {
            get
            {
                return this.inputReferenceFieldSpecified;
            }
            set
            {
                this.inputReferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal OutputReference
        {
            get
            {
                return this.outputReferenceField;
            }
            set
            {
                this.outputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutputReferenceSpecified
        {
            get
            {
                return this.outputReferenceFieldSpecified;
            }
            set
            {
                this.outputReferenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class CommonOutputType
    {
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        private string outputReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OutputReference
        {
            get
            {
                return this.outputReferenceField;
            }
            set
            {
                this.outputReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public partial class LocalisedString
    {
        
        private LangageType langField;
        
        private bool langFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LangageType Lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LangSpecified
        {
            get
            {
                return this.langFieldSpecified;
            }
            set
            {
                this.langFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public enum LangageType
    {
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public partial class StatusType
    {
        
        private string codeField;
        
        private LocalisedString[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LocalisedString[] Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetInsurabilityAsFlatResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetInsurabilityResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:protocol:v1")]
    public partial class ResponseType
    {
        
        private StatusType statusField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1")]
    public partial class GetInsurabilityAsFlatResponseType : ResponseType
    {
        
        private CommonOutputType commonOutputField;
        
        private RecordCommonOutputType recordCommonOutputField;
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonOutputType CommonOutput
        {
            get
            {
                return this.commonOutputField;
            }
            set
            {
                this.commonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RecordCommonOutputType RecordCommonOutput
        {
            get
            {
                return this.recordCommonOutputField;
            }
            set
            {
                this.recordCommonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1")]
    public partial class GetInsurabilityResponseType : ResponseType
    {
        
        private CommonOutputType commonOutputField;
        
        private RecordCommonOutputType recordCommonOutputField;
        
        private SingleInsurabilityResponseType responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonOutputType CommonOutput
        {
            get
            {
                return this.commonOutputField;
            }
            set
            {
                this.commonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RecordCommonOutputType RecordCommonOutput
        {
            get
            {
                return this.recordCommonOutputField;
            }
            set
            {
                this.recordCommonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SingleInsurabilityResponseType Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class SingleInsurabilityRequestType
    {
        
        private CareReceiverIdType careReceiverIdField;
        
        private InsurabilityRequestDetailType insurabilityRequestDetailField;
        
        private MessageNameType messageNameField;
        
        private bool messageNameFieldSpecified;
        
        private string versionField;
        
        private bool duplicateField;
        
        private bool duplicateFieldSpecified;
        
        private bool testFlagField;
        
        private bool testFlagFieldSpecified;
        
        private string senderReferenceField;
        
        private string receiverReferenceField;
        
        private bool synchronousField;
        
        private bool synchronousFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CareReceiverIdType CareReceiverId
        {
            get
            {
                return this.careReceiverIdField;
            }
            set
            {
                this.careReceiverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InsurabilityRequestDetailType InsurabilityRequestDetail
        {
            get
            {
                return this.insurabilityRequestDetailField;
            }
            set
            {
                this.insurabilityRequestDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MessageNameType MessageName
        {
            get
            {
                return this.messageNameField;
            }
            set
            {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageNameSpecified
        {
            get
            {
                return this.messageNameFieldSpecified;
            }
            set
            {
                this.messageNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Duplicate
        {
            get
            {
                return this.duplicateField;
            }
            set
            {
                this.duplicateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuplicateSpecified
        {
            get
            {
                return this.duplicateFieldSpecified;
            }
            set
            {
                this.duplicateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool TestFlag
        {
            get
            {
                return this.testFlagField;
            }
            set
            {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestFlagSpecified
        {
            get
            {
                return this.testFlagFieldSpecified;
            }
            set
            {
                this.testFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SenderReference
        {
            get
            {
                return this.senderReferenceField;
            }
            set
            {
                this.senderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReceiverReference
        {
            get
            {
                return this.receiverReferenceField;
            }
            set
            {
                this.receiverReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Synchronous
        {
            get
            {
                return this.synchronousField;
            }
            set
            {
                this.synchronousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SynchronousSpecified
        {
            get
            {
                return this.synchronousFieldSpecified;
            }
            set
            {
                this.synchronousFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class RecordCommonInputType
    {
        
        private decimal inputReferenceField;
        
        private bool inputReferenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InputReferenceSpecified
        {
            get
            {
                return this.inputReferenceFieldSpecified;
            }
            set
            {
                this.inputReferenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class CareProviderType
    {
        
        private NihiiType nihiiField;
        
        private IdType physicalPersonField;
        
        private IdType organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdType PhysicalPerson
        {
            get
            {
                return this.physicalPersonField;
            }
            set
            {
                this.physicalPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdType Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class NihiiType : SelfRefType
    {
        
        private string qualityField;
        
        private ValueRefString valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class ValueRefString
    {
        
        private string valueRefField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueRef
        {
            get
            {
                return this.valueRefField;
            }
            set
            {
                this.valueRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NihiiType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public abstract partial class SelfRefType
    {
        
        private string idField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public abstract partial class AbstractIdType : SelfRefType
    {
        
        private ValueRefString nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValueRefString Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class PackageType : AbstractIdType
    {
        
        private LicenseType licenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LicenseType License
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class LicenseType
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class IdType : AbstractIdType
    {
        
        private NihiiType nihiiField;
        
        private ValueRefString ssinField;
        
        private ValueRefString cbeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString Ssin
        {
            get
            {
                return this.ssinField;
            }
            set
            {
                this.ssinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ValueRefString Cbe
        {
            get
            {
                return this.cbeField;
            }
            set
            {
                this.cbeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:genericinsurability:core:v1")]
    public partial class OriginType
    {
        
        private PackageType packageField;
        
        private ValueRefString siteIDField;
        
        private CareProviderType careProviderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PackageType Package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CareProviderType CareProvider
        {
            get
            {
                return this.careProviderField;
            }
            set
            {
                this.careProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetInsurabilityAsXmlOrFlatRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:protocol:v1")]
    public partial class RequestType
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInsurabilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsurabilityRequest", Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityRequest1;
        
        public getInsurabilityRequest()
        {
        }
        
        public getInsurabilityRequest(Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityRequest1)
        {
            this.GetInsurabilityRequest1 = GetInsurabilityRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInsurabilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsurabilityResponse", Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.GenIns.GetInsurabilityResponseType GetInsurabilityResponse1;
        
        public getInsurabilityResponse()
        {
        }
        
        public getInsurabilityResponse(Egelke.EHealth.Client.GenIns.GetInsurabilityResponseType GetInsurabilityResponse1)
        {
            this.GetInsurabilityResponse1 = GetInsurabilityResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInsurabilityAsFlatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsurabilityAsFlatRequest", Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityAsFlatRequest1;
        
        public getInsurabilityAsFlatRequest()
        {
        }
        
        public getInsurabilityAsFlatRequest(Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityAsFlatRequest1)
        {
            this.GetInsurabilityAsFlatRequest1 = GetInsurabilityAsFlatRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInsurabilityAsFlatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsurabilityAsFlatResponse", Namespace="urn:be:fgov:ehealth:genericinsurability:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.GenIns.GetInsurabilityAsFlatResponseType GetInsurabilityAsFlatResponse1;
        
        public getInsurabilityAsFlatResponse()
        {
        }
        
        public getInsurabilityAsFlatResponse(Egelke.EHealth.Client.GenIns.GetInsurabilityAsFlatResponseType GetInsurabilityAsFlatResponse1)
        {
            this.GetInsurabilityAsFlatResponse1 = GetInsurabilityAsFlatResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenericInsurabilityPortTypeChannel : Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenericInsurabilityPortTypeClient : System.ServiceModel.ClientBase<Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType>, Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType
    {
        
        public GenericInsurabilityPortTypeClient()
        {
        }
        
        public GenericInsurabilityPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GenericInsurabilityPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GenericInsurabilityPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GenericInsurabilityPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Egelke.EHealth.Client.GenIns.getInsurabilityResponse Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType.getInsurability(Egelke.EHealth.Client.GenIns.getInsurabilityRequest request)
        {
            return base.Channel.getInsurability(request);
        }
        
        public Egelke.EHealth.Client.GenIns.GetInsurabilityResponseType getInsurability(Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityRequest1)
        {
            Egelke.EHealth.Client.GenIns.getInsurabilityRequest inValue = new Egelke.EHealth.Client.GenIns.getInsurabilityRequest();
            inValue.GetInsurabilityRequest1 = GetInsurabilityRequest1;
            Egelke.EHealth.Client.GenIns.getInsurabilityResponse retVal = ((Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType)(this)).getInsurability(inValue);
            return retVal.GetInsurabilityResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatResponse Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType.getInsurabilityAsFlat(Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatRequest request)
        {
            return base.Channel.getInsurabilityAsFlat(request);
        }
        
        public Egelke.EHealth.Client.GenIns.GetInsurabilityAsFlatResponseType getInsurabilityAsFlat(Egelke.EHealth.Client.GenIns.GetInsurabilityAsXmlOrFlatRequestType GetInsurabilityAsFlatRequest1)
        {
            Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatRequest inValue = new Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatRequest();
            inValue.GetInsurabilityAsFlatRequest1 = GetInsurabilityAsFlatRequest1;
            Egelke.EHealth.Client.GenIns.getInsurabilityAsFlatResponse retVal = ((Egelke.EHealth.Client.GenIns.GenericInsurabilityPortType)(this)).getInsurabilityAsFlat(inValue);
            return retVal.GetInsurabilityAsFlatResponse1;
        }
    }
}
