// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.31926
//    <NameSpace>Siemens.EHealth.Etee.Crypto.Library.Xsd.V1</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Siemens.EHealth.Etee.Crypto.Library.Xsd.V1 {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=false)]
    public partial class GetNewKeyRequestContent {
        
        private List<CredentialType> allowedReaderField;
        
        private List<CredentialType> exludedReaderField;
        
        private byte[] eTKField;
        
        private DeletionStrategyType deletionStrategyField;
        
        [System.Xml.Serialization.XmlElementAttribute("AllowedReader")]
        public List<CredentialType> AllowedReader {
            get {
                return this.allowedReaderField;
            }
            set {
                this.allowedReaderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExludedReader")]
        public List<CredentialType> ExludedReader {
            get {
                return this.exludedReaderField;
            }
            set {
                this.exludedReaderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ETK {
            get {
                return this.eTKField;
            }
            set {
                this.eTKField = value;
            }
        }
        
        public DeletionStrategyType DeletionStrategy {
            get {
                return this.deletionStrategyField;
            }
            set {
                this.deletionStrategyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=true)]
    public partial class CredentialType {
        
        private string namespaceField;
        
        private string nameField;
        
        private List<string> valueField;
        
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public List<string> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=true)]
    public partial class DeletionStrategyType {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=false)]
    public partial class GetNewKeyResponseContent {
        
        private byte[] newKeyIdentifierField;
        
        private byte[] newKeyField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] NewKeyIdentifier {
            get {
                return this.newKeyIdentifierField;
            }
            set {
                this.newKeyIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] NewKey {
            get {
                return this.newKeyField;
            }
            set {
                this.newKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=false)]
    public partial class GetKeyRequestContent {
        
        private byte[] keyIdentifierField;
        
        private byte[] eTKField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] KeyIdentifier {
            get {
                return this.keyIdentifierField;
            }
            set {
                this.keyIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ETK {
            get {
                return this.eTKField;
            }
            set {
                this.eTKField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol", IsNullable=false)]
    public partial class GetKeyResponseContent {
        
        private byte[] keyField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
}
