//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egelke.EHealth.Client.Dmf
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SystemError : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SystemError", "urn:be:fgov:ehealth:errors:soa:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SOAErrorType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SOAErrorType", "urn:be:fgov:ehealth:errors:soa:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ErrorType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ErrorType", "urn:be:fgov:ehealth:errors:core:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", ConfigurationName="DmfConsultation", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign)]
    public interface GlobalMedicalFileConsultationPortType
    {
        
        // CODEGEN: Generating message contract since the operation consultGlobalMedicalFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:ConsultGlobalMedicalFile", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.Dmf.SystemError), Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:ConsultGlobalMedicalFile", Name="SystemError", Namespace="urn:be:fgov:ehealth:errors:soa:v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse consultGlobalMedicalFile(Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:ConsultGlobalMedicalFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse> consultGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1")]
    public partial class SendRequestType : RequestType
    {
        
        private CommonInputType commonInputField;
        
        private RoutingType routingField;
        
        private BlobType detailField;
        
        private base64Binary xadesTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonInputType CommonInput
        {
            get
            {
                return this.commonInputField;
            }
            set
            {
                this.commonInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RoutingType Routing
        {
            get
            {
                return this.routingField;
            }
            set
            {
                this.routingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BlobType Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public base64Binary XadesT
        {
            get
            {
                return this.xadesTField;
            }
            set
            {
                this.xadesTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class CommonInputType
    {
        
        private RequestType1 requestField;
        
        private OriginType originField;
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestType1 Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OriginType Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestType", Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class RequestType1
    {
        
        private bool isTestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsTest
        {
            get
            {
                return this.isTestField;
            }
            set
            {
                this.isTestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class CommonOutputType
    {
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        private string outputReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OutputReference
        {
            get
            {
                return this.outputReferenceField;
            }
            set
            {
                this.outputReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1")]
    public partial class ResponseReturnType
    {
        
        private CommonOutputType commonOutputField;
        
        private BlobType detailField;
        
        private base64Binary xadesTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonOutputType CommonOutput
        {
            get
            {
                return this.commonOutputField;
            }
            set
            {
                this.commonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BlobType Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public base64Binary XadesT
        {
            get
            {
                return this.xadesTField;
            }
            set
            {
                this.xadesTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class BlobType
    {
        
        private string contentTypeField;
        
        private string contentEncodingField;
        
        private byte[] hashValueField;
        
        private string idField;
        
        private byte[] valueField;
        
        public BlobType()
        {
            this.contentEncodingField = "deflate";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("deflate")]
        public string ContentEncoding
        {
            get
            {
                return this.contentEncodingField;
            }
            set
            {
                this.contentEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] HashValue
        {
            get
            {
                return this.hashValueField;
            }
            set
            {
                this.hashValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public partial class LocalisedString
    {
        
        private LangageType langField;
        
        private bool langFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LangageType Lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LangSpecified
        {
            get
            {
                return this.langFieldSpecified;
            }
            set
            {
                this.langFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public enum LangageType
    {
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:core:v1")]
    public partial class StatusType
    {
        
        private string codeField;
        
        private LocalisedString[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LocalisedString[] Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:protocol:v1")]
    public partial class ResponseType
    {
        
        private StatusType statusField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1")]
    public partial class SendResponseType : ResponseType
    {
        
        private ResponseReturnType returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseReturnType Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class PeriodType
    {
        
        private System.DateTime startField;
        
        private System.DateTime endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime Start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime End
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class CareReceiverIdType
    {
        
        private string ssinField;
        
        private string regNrWithMutField;
        
        private string mutualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ssin
        {
            get
            {
                return this.ssinField;
            }
            set
            {
                this.ssinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegNrWithMut
        {
            get
            {
                return this.regNrWithMutField;
            }
            set
            {
                this.regNrWithMutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mutuality
        {
            get
            {
                return this.mutualityField;
            }
            set
            {
                this.mutualityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class RoutingType
    {
        
        private CareReceiverIdType careReceiverField;
        
        private System.DateTime referenceDateField;
        
        private PeriodType periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CareReceiverIdType CareReceiver
        {
            get
            {
                return this.careReceiverField;
            }
            set
            {
                this.careReceiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class PartyType
    {
        
        private IdType physicalPersonField;
        
        private IdType organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdType PhysicalPerson
        {
            get
            {
                return this.physicalPersonField;
            }
            set
            {
                this.physicalPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdType Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class IdType : AbstractIdType
    {
        
        private NihiiType nihiiField;
        
        private ValueRefString ssinField;
        
        private ValueRefString cbeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString Ssin
        {
            get
            {
                return this.ssinField;
            }
            set
            {
                this.ssinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ValueRefString Cbe
        {
            get
            {
                return this.cbeField;
            }
            set
            {
                this.cbeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class NihiiType : SelfRefType
    {
        
        private string qualityField;
        
        private ValueRefString valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class ValueRefString
    {
        
        private string valueRefField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueRef
        {
            get
            {
                return this.valueRefField;
            }
            set
            {
                this.valueRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NihiiType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public abstract partial class SelfRefType
    {
        
        private string idField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public abstract partial class AbstractIdType : SelfRefType
    {
        
        private ValueRefString nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValueRefString Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class PackageType : AbstractIdType
    {
        
        private LicenseType licenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LicenseType License
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class LicenseType
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class CareProviderType
    {
        
        private NihiiType nihiiField;
        
        private IdType physicalPersonField;
        
        private IdType organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdType PhysicalPerson
        {
            get
            {
                return this.physicalPersonField;
            }
            set
            {
                this.physicalPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdType Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:globalmedicalfile:core:v1")]
    public partial class OriginType
    {
        
        private PackageType packageField;
        
        private ValueRefString siteIDField;
        
        private CareProviderType careProviderField;
        
        private PartyType senderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PackageType Package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValueRefString SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CareProviderType CareProvider
        {
            get
            {
                return this.careProviderField;
            }
            set
            {
                this.careProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartyType Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:fgov:ehealth:commons:protocol:v1")]
    public partial class RequestType
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultGlobalMedicalFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultGlobalMedicalFileRequest", Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.Dmf.SendRequestType ConsultGlobalMedicalFileRequest1;
        
        public consultGlobalMedicalFileRequest()
        {
        }
        
        public consultGlobalMedicalFileRequest(Egelke.EHealth.Client.Dmf.SendRequestType ConsultGlobalMedicalFileRequest1)
        {
            this.ConsultGlobalMedicalFileRequest1 = ConsultGlobalMedicalFileRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultGlobalMedicalFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultGlobalMedicalFileResponse", Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.Dmf.SendResponseType ConsultGlobalMedicalFileResponse1;
        
        public consultGlobalMedicalFileResponse()
        {
        }
        
        public consultGlobalMedicalFileResponse(Egelke.EHealth.Client.Dmf.SendResponseType ConsultGlobalMedicalFileResponse1)
        {
            this.ConsultGlobalMedicalFileResponse1 = ConsultGlobalMedicalFileResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalMedicalFileConsultationPortTypeChannel : Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalMedicalFileConsultationPortTypeClient : System.ServiceModel.ClientBase<Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType>, Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType
    {
        
        public GlobalMedicalFileConsultationPortTypeClient()
        {
        }
        
        public GlobalMedicalFileConsultationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GlobalMedicalFileConsultationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GlobalMedicalFileConsultationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GlobalMedicalFileConsultationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType.consultGlobalMedicalFile(Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest request)
        {
            return base.Channel.consultGlobalMedicalFile(request);
        }
        
        public Egelke.EHealth.Client.Dmf.SendResponseType consultGlobalMedicalFile(Egelke.EHealth.Client.Dmf.SendRequestType ConsultGlobalMedicalFileRequest1)
        {
            Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest inValue = new Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest();
            inValue.ConsultGlobalMedicalFileRequest1 = ConsultGlobalMedicalFileRequest1;
            Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse retVal = ((Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType)(this)).consultGlobalMedicalFile(inValue);
            return retVal.ConsultGlobalMedicalFileResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse> Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType.consultGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest request)
        {
            return base.Channel.consultGlobalMedicalFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileResponse> consultGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.SendRequestType ConsultGlobalMedicalFileRequest1)
        {
            Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest inValue = new Egelke.EHealth.Client.Dmf.consultGlobalMedicalFileRequest();
            inValue.ConsultGlobalMedicalFileRequest1 = ConsultGlobalMedicalFileRequest1;
            return ((Egelke.EHealth.Client.Dmf.GlobalMedicalFileConsultationPortType)(this)).consultGlobalMedicalFileAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", ConfigurationName = "DmfNotification", ProtectionLevel = System.Net.Security.ProtectionLevel.Sign)]
    public interface GlobalMedicalFileNotificationPortType
    {
        
        // CODEGEN: Generating message contract since the operation notifyGlobalMedicalFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:NotifyGlobalMedicalFile", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.Dmf.SystemError), Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:NotifyGlobalMedicalFile", Name="SystemError", Namespace="urn:be:fgov:ehealth:errors:soa:v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse notifyGlobalMedicalFile(Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1:NotifyGlobalMedicalFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse> notifyGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyGlobalMedicalFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyGlobalMedicalFileRequest", Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.Dmf.SendRequestType NotifyGlobalMedicalFileRequest1;
        
        public notifyGlobalMedicalFileRequest()
        {
        }
        
        public notifyGlobalMedicalFileRequest(Egelke.EHealth.Client.Dmf.SendRequestType NotifyGlobalMedicalFileRequest1)
        {
            this.NotifyGlobalMedicalFileRequest1 = NotifyGlobalMedicalFileRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyGlobalMedicalFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyGlobalMedicalFileResponse", Namespace="urn:be:fgov:ehealth:globalmedicalfile:protocol:v1", Order=0)]
        public Egelke.EHealth.Client.Dmf.SendResponseType NotifyGlobalMedicalFileResponse1;
        
        public notifyGlobalMedicalFileResponse()
        {
        }
        
        public notifyGlobalMedicalFileResponse(Egelke.EHealth.Client.Dmf.SendResponseType NotifyGlobalMedicalFileResponse1)
        {
            this.NotifyGlobalMedicalFileResponse1 = NotifyGlobalMedicalFileResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalMedicalFileNotificationPortTypeChannel : Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalMedicalFileNotificationPortTypeClient : System.ServiceModel.ClientBase<Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType>, Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType
    {
        
        public GlobalMedicalFileNotificationPortTypeClient()
        {
        }
        
        public GlobalMedicalFileNotificationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GlobalMedicalFileNotificationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GlobalMedicalFileNotificationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GlobalMedicalFileNotificationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType.notifyGlobalMedicalFile(Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest request)
        {
            return base.Channel.notifyGlobalMedicalFile(request);
        }
        
        public Egelke.EHealth.Client.Dmf.SendResponseType notifyGlobalMedicalFile(Egelke.EHealth.Client.Dmf.SendRequestType NotifyGlobalMedicalFileRequest1)
        {
            Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest inValue = new Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest();
            inValue.NotifyGlobalMedicalFileRequest1 = NotifyGlobalMedicalFileRequest1;
            Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse retVal = ((Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType)(this)).notifyGlobalMedicalFile(inValue);
            return retVal.NotifyGlobalMedicalFileResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse> Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType.notifyGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest request)
        {
            return base.Channel.notifyGlobalMedicalFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileResponse> notifyGlobalMedicalFileAsync(Egelke.EHealth.Client.Dmf.SendRequestType NotifyGlobalMedicalFileRequest1)
        {
            Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest inValue = new Egelke.EHealth.Client.Dmf.notifyGlobalMedicalFileRequest();
            inValue.NotifyGlobalMedicalFileRequest1 = NotifyGlobalMedicalFileRequest1;
            return ((Egelke.EHealth.Client.Dmf.GlobalMedicalFileNotificationPortType)(this)).notifyGlobalMedicalFileAsync(inValue);
        }
    }
}
