//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egelke.EHealth.Client.GenAsync
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="urn:be:cin:types:v1")]
    public partial class FaultType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FaultCodeField;
        
        private string FaultSourceField;
        
        private Egelke.EHealth.Client.GenAsync.StringLangType MessageField;
        
        private Egelke.EHealth.Client.GenAsync.DetailsType DetailsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultSource
        {
            get
            {
                return this.FaultSourceField;
            }
            set
            {
                this.FaultSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Egelke.EHealth.Client.GenAsync.StringLangType Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public Egelke.EHealth.Client.GenAsync.DetailsType Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class StringLangType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("StringLangType", "urn:be:cin:types:v1");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DetailsType", Namespace="urn:be:cin:types:v1", ItemName="Detail")]
    public class DetailsType : System.Collections.Generic.List<Egelke.EHealth.Client.GenAsync.DetailType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailType", Namespace="urn:be:cin:types:v1")]
    public partial class DetailType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DetailCodeField;
        
        private string DetailSourceField;
        
        private string LocationField;
        
        private Egelke.EHealth.Client.GenAsync.StringLangType MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string DetailCode
        {
            get
            {
                return this.DetailCodeField;
            }
            set
            {
                this.DetailCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string DetailSource
        {
            get
            {
                return this.DetailSourceField;
            }
            set
            {
                this.DetailSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Egelke.EHealth.Client.GenAsync.StringLangType Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.Sign, Namespace = "urn:be:cin:nip:async:generic", ConfigurationName = "GenericAsyncV1")]
    public interface GenericAsync
    {
        
        // CODEGEN: Parameter 'Xadest' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:async:generic:post:msg", ReplyAction="urn:be:cin:nip:async:generic:post:tack")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.GenAsync.FaultType), Action="urn:be:cin:nip:async:generic:post:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Egelke.EHealth.Client.GenAsync.postResponse post(Egelke.EHealth.Client.GenAsync.postRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:async:generic:get:query", ReplyAction="urn:be:cin:nip:async:generic:get:msgs")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.GenAsync.FaultType), Action="urn:be:cin:nip:async:generic:get:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Egelke.EHealth.Client.GenAsync.Responses get(Egelke.EHealth.Client.GenAsync.OrigineType Origin, Egelke.EHealth.Client.GenAsync.MsgQuery MsgQuery, Egelke.EHealth.Client.GenAsync.Query TAckQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:async:generic:confirm:hash", ReplyAction="urn:be:cin:nip:async:generic:confirm:return")]
        [System.ServiceModel.FaultContractAttribute(typeof(Egelke.EHealth.Client.GenAsync.FaultType), Action="urn:be:cin:nip:async:generic:confirm:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SelfRefType))]
        void confirm(Egelke.EHealth.Client.GenAsync.OrigineType Origin, string MsgHashValues, string TAckContents);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class CommonInputType
    {
        
        private RequestType requestField;
        
        private OrigineType originField;
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OrigineType Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class RequestType
    {
        
        private bool isTestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsTest
        {
            get
            {
                return this.isTestField;
            }
            set
            {
                this.isTestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class TAckResponse
    {
        
        private TAck tAckField;
        
        private base64Binary xadestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TAck TAck
        {
            get
            {
                return this.tAckField;
            }
            set
            {
                this.tAckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Xades-t", Order=1)]
        public base64Binary Xadest
        {
            get
            {
                return this.xadestField;
            }
            set
            {
                this.xadestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class TAck
    {
        
        private string issuerField;
        
        private string appliesToField;
        
        private string resultMajorField;
        
        private string resultMinorField;
        
        private string resultMessageField;
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Issuer
        {
            get
            {
                return this.issuerField;
            }
            set
            {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppliesTo
        {
            get
            {
                return this.appliesToField;
            }
            set
            {
                this.appliesToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ResultMajor
        {
            get
            {
                return this.resultMajorField;
            }
            set
            {
                this.resultMajorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ResultMinor
        {
            get
            {
                return this.resultMinorField;
            }
            set
            {
                this.resultMinorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class CommonOutputType
    {
        
        private string inputReferenceField;
        
        private string nIPReferenceField;
        
        private string outputReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InputReference
        {
            get
            {
                return this.inputReferenceField;
            }
            set
            {
                this.inputReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NIPReference
        {
            get
            {
                return this.nIPReferenceField;
            }
            set
            {
                this.nIPReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OutputReference
        {
            get
            {
                return this.outputReferenceField;
            }
            set
            {
                this.outputReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class MsgResponse
    {
        
        private CommonOutputType commonOutputField;
        
        private Blob detailField;
        
        private base64Binary xadestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CommonOutputType CommonOutput
        {
            get
            {
                return this.commonOutputField;
            }
            set
            {
                this.commonOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Blob Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Xades-t", Order=2)]
        public base64Binary Xadest
        {
            get
            {
                return this.xadestField;
            }
            set
            {
                this.xadestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class Blob
    {
        
        private string contentTypeField;
        
        private string contentEncodingField;
        
        private string messageNameField;
        
        private byte[] hashValueField;
        
        private string idField;
        
        private byte[] valueField;
        
        public Blob()
        {
            this.contentEncodingField = "deflate";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentEncoding
        {
            get
            {
                return this.contentEncodingField;
            }
            set
            {
                this.contentEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageName
        {
            get
            {
                return this.messageNameField;
            }
            set
            {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] HashValue
        {
            get
            {
                return this.hashValueField;
            }
            set
            {
                this.hashValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class Responses
    {
        
        private MsgResponse[] msgResponseField;
        
        private TAckResponse[] tAckResponseField;
        
        private int msgCountField;
        
        private int tAckCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MsgResponse", Order=0)]
        public MsgResponse[] MsgResponse
        {
            get
            {
                return this.msgResponseField;
            }
            set
            {
                this.msgResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAckResponse", Order=1)]
        public TAckResponse[] TAckResponse
        {
            get
            {
                return this.tAckResponseField;
            }
            set
            {
                this.tAckResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MsgCount
        {
            get
            {
                return this.msgCountField;
            }
            set
            {
                this.msgCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TAckCount
        {
            get
            {
                return this.tAckCountField;
            }
            set
            {
                this.tAckCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MsgQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class Query
    {
        
        private int maxField;
        
        private bool includeField;
        
        public Query()
        {
            this.maxField = 100;
            this.includeField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int Max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:async:generic")]
    public partial class MsgQuery : Query
    {
        
        private string messageNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageNames
        {
            get
            {
                return this.messageNamesField;
            }
            set
            {
                this.messageNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class CareProviderType
    {
        
        private NihiiType nihiiField;
        
        private IdType physicalPersonField;
        
        private IdType organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdType PhysicalPerson
        {
            get
            {
                return this.physicalPersonField;
            }
            set
            {
                this.physicalPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdType Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class NihiiType : SelfRefType
    {
        
        private string qualityField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NihiiType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class SelfRefType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public abstract partial class AbstractIdType : SelfRefType
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class IdType : AbstractIdType
    {
        
        private NihiiType nihiiField;
        
        private string ssinField;
        
        private string cbeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NihiiType Nihii
        {
            get
            {
                return this.nihiiField;
            }
            set
            {
                this.nihiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ssin
        {
            get
            {
                return this.ssinField;
            }
            set
            {
                this.ssinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cbe
        {
            get
            {
                return this.cbeField;
            }
            set
            {
                this.cbeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class PackageType : AbstractIdType
    {
        
        private LicenseType licenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LicenseType License
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class LicenseType
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:mycarenet:esb:common:v2")]
    public partial class OrigineType
    {
        
        private PackageType packageField;
        
        private string siteIDField;
        
        private CareProviderType careProviderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PackageType Package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CareProviderType CareProvider
        {
            get
            {
                return this.careProviderField;
            }
            set
            {
                this.careProviderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="post", WrapperNamespace="urn:be:cin:nip:async:generic", IsWrapped=true)]
    public partial class postRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:async:generic", Order=0)]
        public Egelke.EHealth.Client.GenAsync.CommonInputType CommonInput;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:async:generic", Order=1)]
        public Egelke.EHealth.Client.GenAsync.Blob Detail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:async:generic", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("Xades-t")]
        public Egelke.EHealth.Client.GenAsync.base64Binary Xadest;
        
        public postRequest()
        {
        }
        
        public postRequest(Egelke.EHealth.Client.GenAsync.CommonInputType CommonInput, Egelke.EHealth.Client.GenAsync.Blob Detail, Egelke.EHealth.Client.GenAsync.base64Binary Xadest)
        {
            this.CommonInput = CommonInput;
            this.Detail = Detail;
            this.Xadest = Xadest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="postResponse", WrapperNamespace="urn:be:cin:nip:async:generic", IsWrapped=true)]
    public partial class postResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:async:generic", Order=0)]
        public Egelke.EHealth.Client.GenAsync.TAck @return;
        
        public postResponse()
        {
        }
        
        public postResponse(Egelke.EHealth.Client.GenAsync.TAck @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenericAsyncChannel : Egelke.EHealth.Client.GenAsync.GenericAsync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenericAsyncClient : System.ServiceModel.ClientBase<Egelke.EHealth.Client.GenAsync.GenericAsync>, Egelke.EHealth.Client.GenAsync.GenericAsync
    {
        
        public GenericAsyncClient()
        {
        }
        
        public GenericAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GenericAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GenericAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GenericAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Egelke.EHealth.Client.GenAsync.postResponse Egelke.EHealth.Client.GenAsync.GenericAsync.post(Egelke.EHealth.Client.GenAsync.postRequest request)
        {
            return base.Channel.post(request);
        }
        
        public Egelke.EHealth.Client.GenAsync.TAck post(Egelke.EHealth.Client.GenAsync.CommonInputType CommonInput, Egelke.EHealth.Client.GenAsync.Blob Detail, Egelke.EHealth.Client.GenAsync.base64Binary Xadest)
        {
            Egelke.EHealth.Client.GenAsync.postRequest inValue = new Egelke.EHealth.Client.GenAsync.postRequest();
            inValue.CommonInput = CommonInput;
            inValue.Detail = Detail;
            inValue.Xadest = Xadest;
            Egelke.EHealth.Client.GenAsync.postResponse retVal = ((Egelke.EHealth.Client.GenAsync.GenericAsync)(this)).post(inValue);
            return retVal.@return;
        }
        
        public Egelke.EHealth.Client.GenAsync.Responses get(Egelke.EHealth.Client.GenAsync.OrigineType Origin, Egelke.EHealth.Client.GenAsync.MsgQuery MsgQuery, Egelke.EHealth.Client.GenAsync.Query TAckQuery)
        {
            return base.Channel.get(Origin, MsgQuery, TAckQuery);
        }
        
        public void confirm(Egelke.EHealth.Client.GenAsync.OrigineType Origin, string MsgHashValues, string TAckContents)
        {
            base.Channel.confirm(Origin, MsgHashValues, TAckContents);
        }
    }
}
