<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sts="urn:be:fgov:ehealth:sts:protocol:v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Saml11TokenService" targetNamespace="urn:be:fgov:ehealth:sts:protocol:v1">

  <documentation>SAML 1.1 Token Service: Version 1.2</documentation>

  <types>
    <xsd:schema>
      <xsd:import namespace="urn:oasis:names:tc:SAML:1.0:protocol" schemaLocation="oasis-sstc-saml-schema-protocol-1.1.xsd"/>
    </xsd:schema>
  </types>

  <message name="RequestMessage">
    <part element="samlp:Request" name="body"/>
  </message>
  <message name="ResponseMessage">
    <part element="samlp:Response" name="body"/>
  </message>

  <portType name="Saml11TokenServicePortType">
    <operation name="RequestSecurityToken">
      <input message="sts:RequestMessage"/>
      <output message="sts:ResponseMessage"/>
    </operation>
  </portType>

  <binding name="Saml11TokenServiceSOAPBinding" type="sts:Saml11TokenServicePortType">
    <soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="RequestSecurityToken">
      <soap11:operation soapAction="urn:be:fgov:ehealth:sts:protocol:v1:RequestSecurityToken"/>
      <input>
        <soap11:body use="literal"/>
      </input>
      <output>
        <soap11:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="Saml11TokenService">
    <port binding="sts:Saml11TokenServiceSOAPBinding" name="Saml11TokenServiceSOAP11">
      <soap11:address location="https://services.ehealth.fgov.be/IAM/Saml11TokenService/v1"/>
    </port>
  </service>

</definitions>
