//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Egelke.EHealth.Client.ChapterIV.Ask {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:io:unsealed:medicalAdvisorAgreement:ask:v1")]
    [System.Xml.Serialization.XmlRootAttribute("Request", Namespace="urn:be:cin:io:unsealed:medicalAdvisorAgreement:ask:v1", IsNullable=false)]
    public partial class RequestType {
        
        private byte[] etkHcpField;
        
        private byte[] kmehrRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] EtkHcp {
            get {
                return this.etkHcpField;
            }
            set {
                this.etkHcpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] KmehrRequest {
            get {
                return this.kmehrRequestField;
            }
            set {
                this.kmehrRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestType", Namespace="urn:be:cin:io:sealed:medicalAdvisorAgreement:ask:v1")]
    [System.Xml.Serialization.XmlRootAttribute("Request", Namespace="urn:be:cin:io:sealed:medicalAdvisorAgreement:ask:v1", IsNullable=false)]
    public partial class RequestType1 {
        
        private CareReceiverIdType careReceiverField;
        
        private System.DateTime agreementStartDateField;
        
        private string unsealKeyIdField;
        
        private byte[] sealedContentField;
        
        /// <remarks/>
        public CareReceiverIdType CareReceiver {
            get {
                return this.careReceiverField;
            }
            set {
                this.careReceiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AgreementStartDate {
            get {
                return this.agreementStartDateField;
            }
            set {
                this.agreementStartDateField = value;
            }
        }
        
        /// <remarks/>
        public string UnsealKeyId {
            get {
                return this.unsealKeyIdField;
            }
            set {
                this.unsealKeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SealedContent {
            get {
                return this.sealedContentField;
            }
            set {
                this.sealedContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class CareReceiverIdType {
        
        private string ssinField;
        
        private string regNrWithMutField;
        
        private string mutualityField;
        
        /// <remarks/>
        public string Ssin {
            get {
                return this.ssinField;
            }
            set {
                this.ssinField = value;
            }
        }
        
        /// <remarks/>
        public string RegNrWithMut {
            get {
                return this.regNrWithMutField;
            }
            set {
                this.regNrWithMutField = value;
            }
        }
        
        /// <remarks/>
        public string Mutuality {
            get {
                return this.mutualityField;
            }
            set {
                this.mutualityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:io:unsealed:medicalAdvisorAgreement:ask:v1")]
    [System.Xml.Serialization.XmlRootAttribute("Response", Namespace="urn:be:cin:io:unsealed:medicalAdvisorAgreement:ask:v1", IsNullable=false)]
    public partial class ResponseType {
        
        private byte[] timestampReplyField;
        
        private byte[] kmehrResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TimestampReply {
            get {
                return this.timestampReplyField;
            }
            set {
                this.timestampReplyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] KmehrResponse {
            get {
                return this.kmehrResponseField;
            }
            set {
                this.kmehrResponseField = value;
            }
        }
    }
}
